INSERT INTO public.topics (name, slug, category) VALUES
  ('Array', 'array', 'data_structures'),
  ('String', 'string', 'data_structures'),
  ('Hash Table', 'hash-table', 'data_structures'),
  ('Linked List', 'linked-list', 'data_structures'),
  ('Stack', 'stack', 'data_structures'),
  ('Queue', 'queue', 'data_structures'),
  ('Tree', 'tree', 'data_structures'),
  ('Binary Tree', 'binary-tree', 'data_structures'),
  ('Binary Search Tree', 'binary-search-tree', 'data_structures'),
  ('Graph', 'graph', 'data_structures'),
  ('Trie', 'trie', 'data_structures'),
  ('Heap', 'heap', 'data_structures'),
  ('Matrix', 'matrix', 'data_structures'),
  ('Dynamic Programming', 'dynamic-programming', 'algorithms'),
  ('Greedy', 'greedy', 'algorithms'),
  ('Backtracking', 'backtracking', 'algorithms'),
  ('Sorting', 'sorting', 'algorithms'),
  ('Binary Search', 'binary-search', 'algorithms'),
  ('Two Pointers', 'two-pointers', 'algorithms'),
  ('Sliding Window', 'sliding-window', 'algorithms'),
  ('Depth-First Search', 'depth-first-search', 'algorithms'),
  ('Breadth-First Search', 'breadth-first-search', 'algorithms'),
  ('Recursion', 'recursion', 'algorithms'),
  ('Divide and Conquer', 'divide-and-conquer', 'algorithms'),
  ('Math', 'math', 'math'),
  ('Bit Manipulation', 'bit-manipulation', 'math'),
  ('Union Find', 'union-find', 'algorithms'),
  ('Monotonic Stack', 'monotonic-stack', 'algorithms');
